### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Flotristant** [meister4ever/quigon#11]
- Usen constantes para la validación de strings y números, por lo general esos valores deberían estar declarados como constantes en la clase que se está validando. Usen la misma constante para validar que se obtiene el comportamiento esperado.
- Si necesitan validar que se lanza una excepción, como acá:

```
   @Test
    public void testWrongLogic() {
        String logic;
        logic = "(";
        tryWrongLogic(logic);
        logic = "a&b";
        tryWrongLogic(logic);
        logic = "()&(b)";
        tryWrongLogic(logic);
        logic = "(a)(b)&(c)";
        tryWrongLogic(logic);
    }
```

Usen:  @Test(expected = WrongLogicException.class ) y dejen así:

```

    private IExpression buildExpression(String logic) throws WrongLogicException{
         return (lBuilder.parse(rules, logic));
    }
```

**Comment by meister4ever** [comment]
Listo! Refactor hecho sobre tests
