### ISSUE TITLE
Builders

### ISSUE THREAD

**Issue by Flotristant** [meister4ever/quigon#12]
Ojo, tienen una confusión entre lo que es un Builder y una Factory. Generalmente, el builder es quien facilita la creación de una entidad y la factory es quien sabe crearlo. Por ejemplo, la clase 'CoursedObject' es una factory, mientras que lo que va haciendo, podría delegarse a un builder, sin necesidad de usar herencia: 
Por ejemplo, en CoursedObject hacen:

```
public void setElements() {
        ComplexElement character = new ComplexElement();
        game.character = character;

        //Create elements
        ComplexElement room0 = new ComplexElement("Room0");
        ComplexElement room1 = new ComplexElement("Room1");
        ComplexElement room2 = new ComplexElement("Room2");
        ComplexElement door0To1 = new ComplexElement("door");
        ComplexElement door1To2 = new ComplexElement("golden_door");
        ComplexElement cursedObject = new ComplexElement("object");
        ComplexElement thief = new ComplexElement("thief");

        //Add elements to the game
        elementsList.add(room0);
        elementsList.add(room1);
        elementsList.add(room2);
        elementsList.add(door0To1);
        elementsList.add(door1To2);
        elementsList.add(cursedObject);
        elementsList.add(thief);

    character.setContainerElement(room0);
        cursedObject.setContainerElement(room0);
        door0To1.setContainerElement(room0);
        thief.setContainerElement(room1);
        door1To2.setContainerElement(room1);

...
}
```

Sería mucho mejor si fuera:

```
public void createGame() {
        GameBuilder builder = new GameBuilder();
    Game game = builder.createNewGame().createCharacter("character").addComplexElement("Room").addComplexElement("Room1").addComplexElement("Room2").addComplexElement("door").putElementIntoContainer("character", "Room0").putElementIntoContainer("object", "Room0").build();
```

(usando constantes para los nombres)

Y el GameBuilder:

```
public GameBuilder putElementIntoContainer(String elementName, String containerName) {
    ComplexElement element = elementsList.stream().filter( e -> e.getName().equals(elementName)).findFirst();
    ComplexElement container = elementsList.stream().filter( e -> e.getName().equals(containerName)).findFirst();
    element.setContainerElement(container);
    return this;
}
```

Esto permitiría tener un solo Builder y una factory para cada caso. Lo cual les facilitaria mucho para la It2.

**Comment by meister4ever** [comment]
![image](https://cloud.githubusercontent.com/assets/11544734/15379167/be22c352-1d40-11e6-95b6-b79c391dd8b3.png)

Según el modelo de Builder, nosotros para la iteración 1 teníamos (y esto se puede ver en el branch mergeNewModel por ejemplo):
![image](https://cloud.githubusercontent.com/assets/11544734/15379285/09f58f02-1d42-11e6-90ed-ad93ee417e88.png)

Es decir, no se ve diferencia ni en el esquema ni en los ejemplos de código entre lo que en muchos lugares se muestra que es un Builder y la implementación que hicimos.
Me gustaría entender, visto el diagrama que comparto, cual es la diferencia entre lo que es un Builder según tu concepción y lo implementado y explicado ahora por nosotros.

**Comment by Flotristant** [comment]
Chicos, lo deje bien explicado en la descripción del issue. El problema que tiene su implementacion es que repiten la misma lógica en todos sus directores, crear complexElement, crear contenedor, meter uno dentro del otro.. Etc. Son tareas que deberían quedar abstraídas en el builder.

**Comment by Flotristant** [comment]
*la misma lógica a en sus builders. 
Si sacan eso, se van a dar cuenta que dejan de ser builders los 'concrete builders'. La idea del diagrama que pusieron es el builder que acompaña una abstract factory, donde cada uno crea las clases que corresponden. No es el caso de uds, hay una sola clase de elementos, no una jerarquía.

**Comment by meister4ever** [comment]
Sisi, estan abstraidas en el Builder. Si te fijas ese ejemplo que nos das de putElementsIntoContainer tenemos en el Builder el método addElementsToContainerRule que hace exactamente eso, y esta abstraido:
    private void addElementsToContainerRule(ContainerRule rule, ComplexElement contained, ComplexElement container,
                                            String failMessage) {
        rule.setElementToValidate(contained);
        rule.setContainerToValidate(container);
        rule.setFailMessage(failMessage);
    }

Esto está en la clase GameBuilder.

**Comment by meister4ever** [comment]
Asumo que la corrección fue sobre la entrega y como si bien mi refactor fue anterior a este issue, al ser sobre el tag Entrega la corrección, el código es otro (de master por ejemplo). El branch de Entrega1 actualizado es mergeNewModel. Con esto solucionado cierro el issue.
