### ISSUE TITLE
Mockear el tiempo, no forzar el juego

### ISSUE THREAD

**Issue by Flotristant** [meister4ever/quigon#18]
La idea en el test de aceptación es probar que efectivamente cuando pasa 'x' tiempo, el juego lanza ciertas acciones de forma automática. Si uds lo fuerzan, no lo están probando. Tiene que ser equivalente a esperar el tiempo.
Esto:
driver.shootTimeEvent(0);
driver.shootTimeEvent(1);
Solamente está forzando el juego a ejecutar acciones que fueron configuradas con timer. No es lo pedido, simulen el tiempo de alguna forma (recuerden que no se puede usar Sleep ni equivalentes, no tienen que esperar el tiempo de forma real, pero el juego tiene que creer que el tiempo pasó realmente).
Necesitan mockear **GameTimeManager**.

**Comment by nexodrone** [comment]
Cambiado con clase abstracta GameTimer cuyos observers son TimeConditions. Su implementacion normal es InternalGameTimer que utiliza timer de java para contar segundos, y mockeada - MockGameTimer usada en Driver que se usa para avanzar tiempo de forma manual. No se estan forzando mas los eventos temporales.
