### ISSUE TITLE
Agregar explicación del diseño de la solución de la it1 en la wiki

### ISSUE THREAD

**Issue by Flotristant** [meister4ever/quigon#7]
La wiki solamente explica la comunicación entre cliente y servidor. El tp se centra en el diseño del motor de los juegos, explicar en la wiki el diseño elegido (con modelo 4+1) y el analisis del ventajas y desventajas. Sería ideal también incluir los diseños descartados y el motivo.

**Comment by meister4ever** [comment]
Listo!. Se pueden encontrar en el menú de la wiki.
